///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Automation_JobLoading.Module
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NormalJob recording.
    /// </summary>
    [TestModule("aa0e41cc-e9b2-473f-8281-3c3e247cd7b4", ModuleType.Recording, 1)]
    public partial class NormalJob : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Automation_JobLoading.Automation_JobLoadingRepository repository.
        /// </summary>
        public static Automation_JobLoading.Automation_JobLoadingRepository repo = Automation_JobLoading.Automation_JobLoadingRepository.Instance;

        static NormalJob instance = new NormalJob();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NormalJob()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NormalJob Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            VAsetting();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenJob0219151851.ThunderRT6UserControlDC' at 21;7.", repo.OpenJob0219151851.ThunderRT6UserControlDCInfo, new RecordItemIndex(1));
            repo.OpenJob0219151851.ThunderRT6UserControlDC.Click("21;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Form0613LoadJobForForDefectV.Element1' at 173;8.", repo.Form0613LoadJobForForDefectV.Element1Info, new RecordItemIndex(2));
            repo.Form0613LoadJobForForDefectV.Element1.MoveTo("173;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SolderPaste3DInspectionSystemKoh.AfxWnd90su' at 891;318.", repo.SolderPaste3DInspectionSystemKoh.AfxWnd90suInfo, new RecordItemIndex(3));
            repo.SolderPaste3DInspectionSystemKoh.AfxWnd90su.MoveTo("891;318");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message0219151921.ThunderRT6UserControlDC' at 38;12.", repo.Message0219151921.ThunderRT6UserControlDCInfo, new RecordItemIndex(4));
            repo.Message0219151921.ThunderRT6UserControlDC.Click("38;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kohyoung3DInspectionHMIForKY3030.아니요N' at 42;18.", repo.Kohyoung3DInspectionHMIForKY3030.아니요NInfo, new RecordItemIndex(5));
            repo.Kohyoung3DInspectionHMIForKY3030.아니요N.Click("42;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.Supervisor' at 47;42.", repo.FormOperator.SupervisorInfo, new RecordItemIndex(6));
            repo.FormOperator.Supervisor.Click("47;42");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.Text' at 22;10.", repo.FormOperator.TextInfo, new RecordItemIndex(7));
            repo.FormOperator.Text.Click("22;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '21077421' with focus on 'FormOperator.Text'.", repo.FormOperator.TextInfo, new RecordItemIndex(8));
            repo.FormOperator.Text.PressKeys("21077421");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.ThunderRT6UserControlDC' at 32;4.", repo.FormOperator.ThunderRT6UserControlDCInfo, new RecordItemIndex(9));
            repo.FormOperator.ThunderRT6UserControlDC.Click("32;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.Setting' at 55;10.", repo.SolderPaste3DInspectionSystemKoh.SettingInfo, new RecordItemIndex(10));
            repo.SolderPaste3DInspectionSystemKoh.Setting.Click("55;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.PCBQty' at 69;29.", repo.SolderPaste3DInspectionSystemKoh.PCBQtyInfo, new RecordItemIndex(11));
            repo.SolderPaste3DInspectionSystemKoh.PCBQty.Click("69;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InputProductionQuantity.Unlimited' at 41;1.", repo.InputProductionQuantity.UnlimitedInfo, new RecordItemIndex(12));
            repo.InputProductionQuantity.Unlimited.Click("41;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InputProductionQuantity.UpDown20WndClass' at 9;4.", repo.InputProductionQuantity.UpDown20WndClassInfo, new RecordItemIndex(13));
            repo.InputProductionQuantity.UpDown20WndClass.Click("9;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'InputProductionQuantity.UpDown20WndClass' at 9;4.", repo.InputProductionQuantity.UpDown20WndClassInfo, new RecordItemIndex(14));
            repo.InputProductionQuantity.UpDown20WndClass.MoveTo("9;4");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'InputProductionQuantity.UpDown20WndClass' at 17;-4.", repo.InputProductionQuantity.UpDown20WndClassInfo, new RecordItemIndex(15));
            repo.InputProductionQuantity.UpDown20WndClass.MoveTo("17;-4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'InputProductionQuantity.Stencil' at 202;2.", repo.InputProductionQuantity.StencilInfo, new RecordItemIndex(16));
            repo.InputProductionQuantity.Stencil.MoveTo("202;2");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InputProductionQuantity.ThunderRT6UserControlDC' at 35;14.", repo.InputProductionQuantity.ThunderRT6UserControlDCInfo, new RecordItemIndex(17));
            repo.InputProductionQuantity.ThunderRT6UserControlDC.Click("35;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Message0219151921.ThunderRT6UserControlDC' at 35;17.", repo.Message0219151921.ThunderRT6UserControlDCInfo, new RecordItemIndex(18));
            repo.Message0219151921.ThunderRT6UserControlDC.Click("35;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Kohyoung3DInspectionHMIForKY3030.아니요N' at 27;14.", repo.Kohyoung3DInspectionHMIForKY3030.아니요NInfo, new RecordItemIndex(19));
            repo.Kohyoung3DInspectionHMIForKY3030.아니요N.Click("27;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.PushButton' at 12;48.", repo.SolderPaste3DInspectionSystemKoh.PushButtonInfo, new RecordItemIndex(20));
            repo.SolderPaste3DInspectionSystemKoh.PushButton.Click("12;48");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.KY3030.DEFECT' at 143;13.", repo.SolderPaste3DInspectionSystemKoh.KY3030.DEFECTInfo, new RecordItemIndex(21));
            repo.SolderPaste3DInspectionSystemKoh.KY3030.DEFECT.Click("143;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.PASS' at 51;75.", repo.SolderPaste3DInspectionSystemKoh.PASSInfo, new RecordItemIndex(22));
            repo.SolderPaste3DInspectionSystemKoh.PASS.Click("51;75");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.KY3030.DEFECT' at 119;21.", repo.SolderPaste3DInspectionSystemKoh.KY3030.DEFECTInfo, new RecordItemIndex(23));
            repo.SolderPaste3DInspectionSystemKoh.KY3030.DEFECT.Click("119;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.PASS' at 81;80.", repo.SolderPaste3DInspectionSystemKoh.PASSInfo, new RecordItemIndex(24));
            repo.SolderPaste3DInspectionSystemKoh.PASS.Click("81;80");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SolderPaste3DInspectionSystemKoh.KY3030.STOP' at 165;15.", repo.SolderPaste3DInspectionSystemKoh.KY3030.STOPInfo, new RecordItemIndex(25));
            repo.SolderPaste3DInspectionSystemKoh.KY3030.STOP.Click("165;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
