///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Automation_JobLoading.Module
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SPIGUI recording.
    /// </summary>
    [TestModule("2eec5a8d-638e-4b35-98aa-6ca8a1ff8b89", ModuleType.Recording, 1)]
    public partial class SPIGUI : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Automation_JobLoading.JobLoading_Repository repository.
        /// </summary>
        public static Automation_JobLoading.JobLoading_Repository repo = Automation_JobLoading.JobLoading_Repository.Instance;

        static SPIGUI instance = new SPIGUI();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SPIGUI()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SPIGUI Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VisionAnalysisToolVersion273.KY3030Start' at 85;9.", repo.VisionAnalysisToolVersion273.KY3030StartInfo, new RecordItemIndex(0));
            //repo.VisionAnalysisToolVersion273.KY3030Start.Click("85;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.BASEPopup.ButtonOK' at 37;6.", repo.SPIGUI.BASEPopup.ButtonOKInfo, new RecordItemIndex(1));
            //repo.SPIGUI.BASEPopup.ButtonOK.Click("37;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator' at 8;35.", repo.FormOperator.SelfInfo, new RecordItemIndex(2));
            //repo.FormOperator.Self.Click("8;35");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.Supervisor1' at 24;30.", repo.FormOperator.Supervisor1Info, new RecordItemIndex(3));
            //repo.FormOperator.Supervisor1.Click("24;30");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.Password' at 67;3.", repo.FormOperator.PasswordInfo, new RecordItemIndex(4));
            //repo.FormOperator.Password.Click("67;3");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '21077421' with focus on 'FormOperator.Password'.", repo.FormOperator.PasswordInfo, new RecordItemIndex(5));
            //repo.FormOperator.Password.PressKeys("21077421");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormOperator.ButtonOK' at 63;8.", repo.FormOperator.ButtonOKInfo, new RecordItemIndex(6));
            //repo.FormOperator.ButtonOK.Click("63;8");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.SkipLoadingLane2' at 7;8.", repo.SPIGUI.LoadJobFile.SkipLoadingLane2Info, new RecordItemIndex(7));
            //repo.SPIGUI.LoadJobFile.SkipLoadingLane2.Click("7;8");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.BASEPopup.Cancel' at 61;10.", repo.SPIGUI.BASEPopup.CancelInfo, new RecordItemIndex(8));
            //repo.SPIGUI.BASEPopup.Cancel.Click("61;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.ButtonOK' at 28;16.", repo.SPIGUI.LoadJobFile.ButtonOKInfo, new RecordItemIndex(9));
            //repo.SPIGUI.LoadJobFile.ButtonOK.Click("28;16");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.BASEPopup.ButtonOK' at 45;3.", repo.SPIGUI.BASEPopup.ButtonOKInfo, new RecordItemIndex(10));
            //repo.SPIGUI.BASEPopup.ButtonOK.Click("45;3");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.ButtonOK' at 51;20.", repo.SPIGUI.LoadJobFile.ButtonOKInfo, new RecordItemIndex(11));
            //repo.SPIGUI.LoadJobFile.ButtonOK.Click("51;20");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SPIGUI.BASEPopup.ButtonOK' at 53;11.", repo.SPIGUI.BASEPopup.ButtonOKInfo, new RecordItemIndex(12));
            //repo.SPIGUI.BASEPopup.ButtonOK.MoveTo("53;11");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SPIGUI.BASEPopup.ButtonOK' at 61;3.", repo.SPIGUI.BASEPopup.ButtonOKInfo, new RecordItemIndex(13));
            //repo.SPIGUI.BASEPopup.ButtonOK.MoveTo("61;3");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.BASEPopup.ButtonOK' at 53;10.", repo.SPIGUI.BASEPopup.ButtonOKInfo, new RecordItemIndex(14));
            //repo.SPIGUI.BASEPopup.ButtonOK.Click("53;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.SkipLoadingLane2' at 27;5.", repo.SPIGUI.LoadJobFile.SkipLoadingLane2Info, new RecordItemIndex(15));
            //repo.SPIGUI.LoadJobFile.SkipLoadingLane2.Click("27;5");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.NormalLane2' at 51;12.", repo.SPIGUI.LoadJobFile.NormalLane2Info, new RecordItemIndex(16));
            //repo.SPIGUI.LoadJobFile.NormalLane2.Click("51;12");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.JobPathLane1' at 127;0.", repo.SPIGUI.LoadJobFile.JobPathLane1Info, new RecordItemIndex(17));
            //repo.SPIGUI.LoadJobFile.JobPathLane1.Click("127;0");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.JobPathLane2' at 130;8.", repo.SPIGUI.LoadJobFile.JobPathLane2Info, new RecordItemIndex(18));
            //repo.SPIGUI.LoadJobFile.JobPathLane2.Click("130;8");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute '(Choose)' to contain the specified value 'yourValue'. Associated repository item: 'SPIGUI.SPIGUI.LoadedJob'", repo.SPIGUI.SPIGUI.LoadedJobInfo, new RecordItemIndex(19));
            //repo.SPIGUI.SPIGUI.LoadedJobInfo.WaitForAttributeContains(5000, "(Choose)", "yourValue");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.SkipLoadingLane2' at 51;6.", repo.SPIGUI.LoadJobFile.SkipLoadingLane2Info, new RecordItemIndex(20));
            //repo.SPIGUI.LoadJobFile.SkipLoadingLane2.Click("51;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.LoadJobFile.ButtonOK' at 61;11.", repo.SPIGUI.LoadJobFile.ButtonOKInfo, new RecordItemIndex(21));
            //repo.SPIGUI.LoadJobFile.ButtonOK.Click("61;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.VisionErrorPopup' at 336;29.", repo.SPIGUI.VisionErrorPopup.SelfInfo, new RecordItemIndex(22));
            //repo.SPIGUI.VisionErrorPopup.Self.Click("336;29");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.VisionErrorPopup.ButtonOK' at 33;9.", repo.SPIGUI.VisionErrorPopup.ButtonOKInfo, new RecordItemIndex(23));
            //repo.SPIGUI.VisionErrorPopup.ButtonOK.Click("33;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.InputProductionQuantity' at 237;2.", repo.SPIGUI.InputProductionQuantity.SelfInfo, new RecordItemIndex(24));
            //repo.SPIGUI.InputProductionQuantity.Self.Click("237;2");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.InputProductionQuantity.ButtonOK' at 24;9.", repo.SPIGUI.InputProductionQuantity.ButtonOKInfo, new RecordItemIndex(25));
            //repo.SPIGUI.InputProductionQuantity.ButtonOK.Click("24;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SPIGUI.InputProductionQuantity' at 287;35.", repo.SPIGUI.InputProductionQuantity.SelfInfo, new RecordItemIndex(26));
            //repo.SPIGUI.InputProductionQuantity.Self.MoveTo("287;35");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.InputProductionQuantity.ButtonOK' at 60;8.", repo.SPIGUI.InputProductionQuantity.ButtonOKInfo, new RecordItemIndex(27));
            //repo.SPIGUI.InputProductionQuantity.ButtonOK.Click("60;8");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
