///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Automation_JobLoading.Module
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The test recording.
    /// </summary>
    [TestModule("f3ea9af1-56cd-4695-9090-b448e25c523b", ModuleType.Recording, 1)]
    public partial class test : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Automation_JobLoading.Automation_JobLoadingRepository repository.
        /// </summary>
        public static Automation_JobLoading.Automation_JobLoadingRepository repo = Automation_JobLoading.Automation_JobLoadingRepository.Instance;

        static test instance = new test();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public test()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static test Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VisionAnalysisToolVersion273.txtJob' at 148;14.", repo.VisionAnalysisToolVersion273.txtJobInfo, new RecordItemIndex(0));
            repo.VisionAnalysisToolVersion273.txtJob.Click("148;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}'.", new RecordItemIndex(1));
            Keyboard.Press("{LControlKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VisionAnalysisToolVersion273.txtJob' at 107;11.", repo.VisionAnalysisToolVersion273.txtJobInfo, new RecordItemIndex(2));
            repo.VisionAnalysisToolVersion273.txtJob.Click("107;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'VisionAnalysisToolVersion273.txtJob'.", repo.VisionAnalysisToolVersion273.txtJobInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.VisionAnalysisToolVersion273.txtJob);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
