///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Automation_JobLoading.Module
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VisionErrorWatch recording.
    /// </summary>
    [TestModule("48c14493-c233-4175-838b-cba424ff21ce", ModuleType.Recording, 1)]
    public partial class VisionErrorWatch : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Automation_JobLoading.JobLoading_Repository repository.
        /// </summary>
        public static Automation_JobLoading.JobLoading_Repository repo = Automation_JobLoading.JobLoading_Repository.Instance;

        static VisionErrorWatch instance = new VisionErrorWatch();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VisionErrorWatch()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VisionErrorWatch Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Screenshot(ReportLevel.Info, "User", "", repo.SPIGUI.VisionErrorPopup.Self, false, new RecordItemIndex(0));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.VisionErrorPopup.ButtonOK' at 51;16.", repo.SPIGUI.VisionErrorPopup.ButtonOKInfo, new RecordItemIndex(1));
            //repo.SPIGUI.VisionErrorPopup.ButtonOK.Click("51;16");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SPIGUI.VisionErrorPopup' at 320;32.", repo.SPIGUI.VisionErrorPopup.SelfInfo, new RecordItemIndex(2));
            //repo.SPIGUI.VisionErrorPopup.Self.Click("320;32");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.ErrorReport' at 51;21.", repo.Explorer.ErrorReportInfo, new RecordItemIndex(3));
            //repo.Explorer.ErrorReport.Click("51;21");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CrashUI.ErrorReport.DumpSaveBtn' at CenterLeft.", repo.CrashUI.ErrorReport.DumpSaveBtnInfo, new RecordItemIndex(4));
            //repo.CrashUI.ErrorReport.DumpSaveBtn.Click(Location.CenterLeft);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CrashUI.ErrorReportDetails.Export' at 27;4.", repo.CrashUI.ErrorReportDetails.ExportInfo, new RecordItemIndex(5));
            //repo.CrashUI.ErrorReportDetails.Export.Click("27;4");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CrashUI.SaveAs.Computer' at 72;29.", repo.CrashUI.SaveAs.ComputerInfo, new RecordItemIndex(6));
            //repo.CrashUI.SaveAs.Computer.Click("72;29");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CrashUI.SaveAs.LocalDiskS' at 62;34.", repo.CrashUI.SaveAs.LocalDiskSInfo, new RecordItemIndex(7));
            //repo.CrashUI.SaveAs.LocalDiskS.DoubleClick("62;34");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CrashUI.SaveAs.Automation' at 70;15.", repo.CrashUI.SaveAs.AutomationInfo, new RecordItemIndex(8));
            //repo.CrashUI.SaveAs.Automation.DoubleClick("70;15");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
